
---------------------- BUSINESS ----------------------

DROP TABLE IF EXISTS UDACITYEXERCISE.PUBLIC.DIM_BUSINESS;

DROP TABLE IF EXISTS UDACITYEXERCISE.PUBLIC.DIM_BUSINESS_ATTRIBUTES;

DROP TABLE IF EXISTS UDACITYEXERCISE.PUBLIC.DIM_BUSINESS_CATEGRORIES;


CREATE TABLE IF NOT EXISTS UDACITYEXERCISE.PUBLIC.DIM_BUSINESS(
    business_id VARCHAR(255) PRIMARY KEY,
    address VARCHAR(255),
    city VARCHAR(255),
    hours VARIANT,
    is_open BOOLEAN,
    latitude DOUBLE,
    longitude DOUBLE,
    name VARCHAR(255),
    postal_code INT,
    review_count INT,
    stars DOUBLE,
    state VARCHAR(50)
);

INSERT INTO UDACITYEXERCISE.PUBLIC.DIM_BUSINESS
SELECT 
    business_id, 
    address,
    city,
    hours,
    is_open, 
    latitude, 
    longitude,
    name,
    postal_code,
    review_count,
    stars,
    state
FROM UDACITYEXERCISE.ODS.BUSINESS;

CREATE TABLE IF NOT EXISTS UDACITYEXERCISE.PUBLIC.DIM_BUSINESS_ATTRIBUTES(
    business_id VARCHAR(255) REFERENCES UDACITYEXERCISE.PUBLIC.DIM_BUSINESS(business_id),
    key VARCHAR(100),
    value TEXT
    );

INSERT INTO UDACITYEXERCISE.PUBLIC.DIM_BUSINESS_ATTRIBUTES
SELECT
    business_id,
    key,
    value
FROM UDACITYEXERCISE.ODS.BUSINESS_ATTRIBUTES;

CREATE TABLE IF NOT EXISTS UDACITYEXERCISE.PUBLIC.DIM_BUSINESS_CATEGRORIES(
    business_id VARCHAR(255) REFERENCES UDACITYEXERCISE.PUBLIC.DIM_BUSINESS(business_id),
    index INT,
    value VARCHAR(255)
    );

INSERT INTO UDACITYEXERCISE.PUBLIC.DIM_BUSINESS_CATEGRORIES
SELECT  
    business_id,
    index,
    value
FROM 
    UDACITYEXERCISE.ODS.BUSINESS_CATEGRORIES;

------------------- CHECKING -------------------
SELECT * FROM UDACITYEXERCISE.PUBLIC.DIM_BUSINESS LIMIT 100;

SELECT * FROM UDACITYEXERCISE.PUBLIC.DIM_BUSINESS_ATTRIBUTES LIMIT 100;

SELECT * FROM UDACITYEXERCISE.PUBLIC.DIM_BUSINESS_CATEGRORIES LIMIT 100;
