---------------------- CHECKIN ----------------------
SELECT * FROM UDACITYEXERCISE.ODS.CHECKIN LIMIT 1;

DROP TABLE IF EXISTS UDACITYEXERCISE.PUBLIC.DIM_CHECKIN;

CREATE TABLE IF NOT EXISTS UDACITYEXERCISE.PUBLIC.DIM_CHECKIN(
    business_id VARCHAR(255) NOT NULL,
    date DATE,
    timestamp TIMESTAMP
    );

INSERT INTO UDACITYEXERCISE.PUBLIC.DIM_CHECKIN
SELECT
    business_id,
    date,
    timestamp
FROM 
    UDACITYEXERCISE.ODS.CHECKIN;

SELECT * FROM UDACITYEXERCISE.PUBLIC.DIM_CHECKIN LIMIT 10
