---------------------- PRECIPITATION ----------------------

DROP TABLE UDACITYEXERCISE.ODS.PRECIPITATION;

CREATE TABLE IF NOT EXISTS UDACITYEXERCISE.ODS.PRECIPITATION(
    date DATE PRIMARY KEY,
    precipitation DOUBLE,
    precipitation_normal DOUBLE
    );

INSERT INTO UDACITYEXERCISE.ODS.PRECIPITATION
SELECT 
    TO_DATE(date::TEXT, 'YYYYMMDD') AS date,
    TRY_TO_DOUBLE(precipitation) AS precipitation,
    TRY_TO_DOUBLE(precipitation_normal) AS precipitation_normal
 FROM UDACITYEXERCISE.STAGING.PRECIPITATION
 ;

SELECT * FROM UDACITYEXERCISE.ODS.PRECIPITATION LIMIT 100;