---------------------- TEMPERATURE ----------------------
DROP TABLE IF EXISTS UDACITYEXERCISE.ODS.TEMPERATURE;

CREATE TABLE IF NOT EXISTS UDACITYEXERCISE.ODS.TEMPERATURE(
    date DATE PRIMARY KEY,
    min DOUBLE,
    max DOUBLE,
    normal_min DOUBLE,
    normal_max DOUBLE
    );

INSERT INTO UDACITYEXERCISE.ODS.TEMPERATURE
SELECT 
    TO_DATE(date::TEXT, 'YYYYMMDD') AS date,
    TRY_TO_DOUBLE(min) AS min,
    TRY_TO_DOUBLE(max) AS max,
    TRY_TO_DOUBLE(normal_min) AS normal_min,
    TRY_TO_DOUBLE(normal_max) AS normal_max
FROM UDACITYEXERCISE.STAGING.TEMPERATURE;

SELECT * FROM UDACITYEXERCISE.ODS.TEMPERATURE LIMIT 100;
